BHFunctioning/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using BHFunctioning.Data;
using BHFunctioning.Models;

namespace BHFunctioning.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _db;
        public readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;

        public AdminController(RoleManager<IdentityRole> roleManager, ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _db = db;
            _userManager = userManager;
            

        }

        public void CheckAdmin()
        {
            if (AdminExistsAsync() == false)
            {
                CreateAdmin();
            }
        }

        private bool CreateAdmin()
        {

            IdentityRole identityRole = new();
            identityRole.Name = "Administrator";
            identityRole.NormalizedName = "Administrator";
            var res = _roleManager.CreateAsync(identityRole);
            if(res != null)
            {
                return true;
            }
            return false;
        }
        private bool AdminExistsAsync()
        {
            bool AdminExist;
            Role admin = new();
            admin.Name = "Administrator";
            var role = _roleManager.FindByNameAsync(admin.Name);

            if(role == null)
            {
                AdminExist = false;
            }
            else
            {
                AdminExist = true;
            }

            return AdminExist;

        }

        //Main page of role management, displays all roles
        [HttpGet]
        public IActionResult ListAllRoles()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public IActionResult AddRoles()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRoles(Role roleObj)
        {
            //System.Diagnostics.Debug.WriteLine("Rolename: " + roleObj.Name);
            if (ModelState.IsValid)
            {
                var role = await _roleManager.FindByNameAsync(roleObj.Name);

                if (role != null)
                {
                    ModelState.AddModelError("Name", "This role already exists!");

                }

                IdentityRole identityRole = new();
                identityRole.Name = roleObj.Name;
                identityRole.NormalizedName = roleObj.Name;

                var result = await _roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListAllRoles");
                }
                

            }
            
                return View(roleObj);
        }
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var roleDb = await _roleManager.FindByIdAsync(id);
            
            EditRoleModel model = new();
            model.Id = roleDb.Id.ToString();
            model.Name = roleDb.Name;
            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, model.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }
            return View(model);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRoleAsync(EditRoleModel obj)
        {
            //id.Id is null for some reason no idea
            var newRole = await _roleManager.FindByIdAsync(obj.Id);
            if (newRole == null)
            {
                ViewData["ErrorMessage"] = $"No role with Id '{obj.Id}' was found";
                return View("Error");
            }
            else
            {
                newRole.Name = obj.Name;
                var res = await _roleManager.UpdateAsync(newRole);
                if (res.Succeeded)
                {
                    return RedirectToAction("ListAllRoles");
                }else
                {  
                    ModelState.AddModelError("Name", "Error editing Role");
                }
            }

            return View(newRole);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var getRole = await _roleManager.FindByIdAsync(id);

            EditRoleModel Tempmodel = new();
            Tempmodel.Id = getRole.Id.ToString();
            Tempmodel.Name = getRole.Name;
            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, Tempmodel.Name))
                {
                    Tempmodel.Users.Add(user.UserName);
                }
            }
            return View(Tempmodel);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRole(EditRoleModel obj)
        {
            
            var newRole = await _roleManager.FindByIdAsync(obj.Id);
            if (newRole == null)
            {
                ViewData["ErrorMessage"] = $"No role with Id '{obj.Id}' was found";
                return View("Error");
            }
            else
            {
                //Check if there are any users in the role before deleting
                foreach (var user in _userManager.Users)
                {
                    if (await _userManager.IsInRoleAsync(user, obj.Name))
                    {
                        ModelState.AddModelError("Name", "There exists users with this role");
                        return View(obj);
                    }
                }

                //deleteing the role 
                var res = await _roleManager.DeleteAsync(newRole);
                if (res.Succeeded)
                {
                    return RedirectToAction("ListAllRoles");
                }
                else
                {
                    ModelState.AddModelError("Name", "Error deleting Role");
                }
            }

            return View(newRole);
        }

        [HttpGet]
        public async Task<IActionResult> EditRoleUser(string id)
        {
            var roleDb = await _roleManager.FindByIdAsync(id);
            
            List<UserRoleModel> listOfUsersInRole = new();

            //Goes through each user and adds them into the list 
            foreach (var user in _userManager.Users)
            {
                UserRoleModel temp = new();
                temp.Id = user.Id;
                temp.Name = user.UserName;
                //Checks if the user has the role and if it does, it will check the checkbox
                if(await _userManager.IsInRoleAsync(user, roleDb.Name))
                {
                    temp.IsSelected = true;
                }
                else
                {
                    temp.IsSelected = false;
                }
                listOfUsersInRole.Add(temp);
                
            }
            return View(listOfUsersInRole);
        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> EditRoleUser(List<UserRoleModel> obj)
        //{
        //    foreach (UserRoleModel tmp in obj)
        //    {

        //    }

        //    return View(newRole);
        //}

    }
}

BHFunctioning/Controllers/DataVizController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BHFunctioning.Models;
using BHFunctioning.Data;
using BHFunctioning.Models;
namespace BHFunctioning.Controllers
{
    public class DataVizController : Controller
    {
        private readonly ApplicationDbContext _db;
        public DataVizController(ApplicationDbContext db)
        {
            _db = db;

        }
        // GET: DataVizController
        public ActionResult Index()
        {
            return View();
        }

        // GET: DataVizController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DataVizController/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: DataVizController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HealthData obj)
        {
            System.Diagnostics.Debug.WriteLine("Medical: " + obj.Medical);
            System.Diagnostics.Debug.WriteLine("ChildDX: "+obj.ChildDx);
            System.Diagnostics.Debug.WriteLine("Selfharm: "+obj.Selfharm);
            System.Diagnostics.Debug.WriteLine("Sofas: "+ obj.Sofas);
            System.Diagnostics.Debug.WriteLine("ClinicalStage: "+obj.ClinicalStage);
            System.Diagnostics.Debug.WriteLine("Circadian: " + obj.Circadian);
            System.Diagnostics.Debug.WriteLine("Tripartite: "+obj.Tripartite);
            System.Diagnostics.Debug.WriteLine("Psychosis: "+obj.Psychosis);
            System.Diagnostics.Debug.WriteLine("NEET: "+ obj.NEET);

            //var _id = _db.Healthdata.SingleOrDefault(
            //    a => a.Medical == obj.Medical && 
            //    a.ChildDx == obj.ChildDx && 
            //    a.Selfharm == obj.Selfharm &&
            //    a.Sofas == obj.Sofas &&
            //    a.ClinicalStage == obj.ClinicalStage &&
            //    a.Circadian == obj.Circadian &&
            //    a.Tripartite == obj.Tripartite &&
            //    a.Psychosis == obj.Psychosis &&
            //    a.NEET == obj.NEET);


            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DataVizController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DataVizController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DataVizController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DataVizController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BHFunctioning/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BHFunctioning</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BHFunctioning.styles.css" asp-append-version="true" />
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (SignInManager.IsSignedIn(User))
                {
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">BHFunctioning</a>
                }
                else
                {
                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">BHFunctioning</a>

                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="DataViz" asp-action="Index">Home</a>
                            </li>
                            @if (User.IsInRole("Administrator"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Admin" asp-action="ListAllRoles">Manage Roles</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BHFunctioning - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BHFunctioning/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>toastr.success('@TempData["success"]')</script> 
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>toastr.error('@TempData["error"]')</script> 
}